import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import Project from "../models/Project.js";
import Drawing from "../models/Drawing.js";
import Estimation from "../models/Estimation.js";
import Timeline from "../models/Timeline.js";

export const exportProjectPDF = async (req, res) => {
  try {
    const { projectId } = req.params;

    const project = await Project.findById(projectId);
    if (!project)
      return res.status(404).json({ message: "Project not found" });

    const drawings = await Drawing.find({ projectId });
    const estimations = await Estimation.find({
      drawingId: { $in: drawings.map(d => d._id) }
    });

    const timelines = await Timeline.find({
      estimationId: { $in: estimations.map(e => e._id) }
    });

    const totalCost = estimations.reduce(
      (sum, e) => sum + e.costBreakdown.totalCost,
      0
    );

    // 🔹 Create PDF
    const doc = new PDFDocument({ margin: 50 });

    const fileName = `project-${projectId}.pdf`;
    const filePath = path.join("reports", fileName);

    doc.pipe(fs.createWriteStream(filePath));

    // 🔹 Title
    doc.fontSize(22).text("Construction Project Report", {
      align: "center"
    });

    doc.moveDown();

    // 🔹 Project Info
    doc.fontSize(16).text("Project Details");
    doc.moveDown(0.5);
    doc.fontSize(12).text(`Project Name: ${project.projectName}`);
    doc.text(`Location: ${project.location}`);
    doc.text(`Project Type: ${project.projectType}`);
    doc.text(`Total Drawings: ${drawings.length}`);
    doc.moveDown();

    // 🔹 Estimation Section
    doc.fontSize(16).text("Estimation Summary");
    doc.moveDown(0.5);

    estimations.forEach((est, index) => {
      doc.fontSize(12).text(`Drawing ${index + 1}:`);
      doc.text(`  Concrete: ${est.quantities.concrete}`);
      doc.text(`  Steel: ${est.quantities.steel}`);
      doc.text(`  Bricks: ${est.quantities.bricks}`);
      doc.text(`  Total Cost: ₹${est.costBreakdown.totalCost}`);
      doc.moveDown();
    });

    // 🔹 Timeline Section
    doc.fontSize(16).text("Timeline");
    doc.moveDown(0.5);

    timelines.forEach(timeline => {
      timeline.phases.forEach(phase => {
        doc.fontSize(12).text(
          `${phase.phaseName}: ${new Date(
            phase.startDate
          ).toDateString()} - ${new Date(
            phase.endDate
          ).toDateString()}`
        );
      });
      doc.moveDown();
    });

    doc.fontSize(14).text(`Total Project Cost: ₹${totalCost}`);
    doc.moveDown();

    doc.text("Generated by AI Construction Planning System", {
      align: "center"
    });

    doc.end();
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);
    // 🔹 Send file to user
    stream.on("finish", () => {
        const absolutePath = path.resolve(filePath);

        res.download(absolutePath, (err) => {
            if (err) {
            console.error("Download error:", err);
            res.status(500).json({ message: "Error downloading file" });
            }
        });
        });

  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};